# Plugin develloped by GFelberg
# Config.yml

# language: en
# Thanks for downloading my plugin. For more plugins, dont forget to look my updates!
# If you find any bugs or ideas to the plugin, pm me at spigot.

# language: br/pt
# Obrigado por baixar meu plugin. Para mais plugins, não esqueça de olhar as atualizações!
# Se você encontrar algum problema ou ter alguma ideia para o plugin, pm no spigot.  

# WARNING!!! This plugin is for Minecraft Versions 1.11+.

# Permissions

# anticurse.anticurse : Access to the AntiCurse Command
# anticurse.admin : Access to the Admin Help Page
# anticurse.reload : Access to Reload the Plugin

# Configuration 1.0
# This configuration will display the AntiCurse Messages

AntiCurse:
  Prefix: '&b[&cAntiCurse&b]&r'
  NoCurse: '&cNo curse were found!'
  Removed: '&aThe curse has been removed!'
  NoItemHand: '&cYou dont have an item in your hand!'

# Configuration 1.1
# This configuration will display the Help Page Messages

Help:
  Page: '&eShows this page'
  Curse: '&eRemoves the curse from the item'
  Reload: '&eReloads the Plugin'
